### ISSUE TITLE
How to change apple II e emulator in window that can read 41 or even 42 tracks disk ?

### ISSUE THREAD

**Issue by ngchungtak** [ct6502/apple2ts#55]
I have 41 tracks disk but it can not be insert into drive 1 or 2 in apple ii e emulator in window ! Please teach me how to change the emulator to 42 tracks version ! I cannot upload the 41 tracks disk,since I cannot pass the gate in log in microsoft.
you can create 41 track disk in software i.e.ciderPress  .To select file new in create diskimage function ,specify size to 328(41 tracks), or 336(42  tracks)blocks from old value 280 blocks.Please teach me how to change the emulator to 41 tracks or even 42 tracks version ! 
Thanks you for your teaching !(320 blocks is 40 track disk)

**Comment by ngchungtak** [comment]
ciderPress is free download software in window, Please download it and then create 41 or 42 tracks disk to test your future amend version in apple ii e emulator in window !

**Comment by ct6502** [comment]
Okay, this is mostly fixed. DSK images can only go up to 40 tracks, because they get converted to WOZ format, and WOZ files can have a maximum of 40 tracks. ProDOS PO disk images can have an arbitrary number of tracks, from 35 up to 8192 (a 32mb image). So if you need more than 40 tracks, your disk had better be in .po, .hdv, or .2mg format.

The zip folder contains 3 files: a 40-track dsk, a 40-track woz, and a 42-track po. All 3 now work in the emulator.
[DiskImages.zip](https://github.com/ct6502/apple2ts/files/14339783/DiskImages.zip)
