### ISSUE TITLE
Backspace generating Left Arrow rather than Delete confusing users/apps

### ISSUE THREAD

**Issue by inexorabletash** [ct6502/apple2ts#73]
**Describe the bug**
I received a bug report (via email) for [A2DeskTop](https://github.com/a2stuff/a2d) that backspace wasn't working in text fields. The root cause is that Apple2TS generates "left arrow" rather than "delete" when the Backspace key is pressed. Shift+Backspace provides a workaround, but this is non-obvious.

**To Reproduce**
1. https://apple2ts.com/?color=white&speed=fast#https://a2desktop.s3.amazonaws.com/A2DeskTop-1.4-beta1-en_800k.2mg
2. Click on the A2.DeskTop disk icon
3. Initiate rename by clicking the icon's name, selecting File > Rename, or just pressing Return (the shortcut)
4. Try to erase the name

**Expected behavior**
Backspace... backspaces.

While generating Left Arrow (0x08) instead of Delete (0x7F) is convenient at the BASIC prompt, any proper text editor like AppleWorks expects Delete - try to delete some text in AppleWorks using Apple2TS! ProDOS 2.4.3's BASIC.SYSTEM 1.7 converts Delete into Left Arrow as a convenience.

**Workarounds**
* Shift+Backspace, which is [special-cased by Apple2TS](https://github.com/ct6502/apple2ts/blob/0374ebdade0be9f5daf5db8929885bfe0bcdf127/src/emulator/utility/utility.ts#L214) to generate Delete (0x7F)
* In A2DeskTop, use Ctrl+F (forward-delete) or Ctrl+X (clear)

**Suggestions**
* Always treat Backspace as Delete
* As above, but add an option to treat Backspace as Left Arrow
* Add a URL option to treat Backspace as Delete, and I can revise the URLs I give out for trying A2D using Apple2TS

**Comment by ct6502** [comment]
Thanks for reporting this!

I have (foolishly?) tried to make the code do the "right" thing. By default we now send the 0x7F rubout/delete character. This fixes the problem with A2DeskTop, Appleworks, and A2osX. However, if the default COUT ($38/$39 === $FD1B) is in effect, then we assume that we're in Applesoft BASIC and we send the backspace like before. Since there may be cases where this is wrong, if the shift key is down then still send the rubout character.

In all the cases I tested, programs that properly handle the delete/rubout have also overridden COUT. If anyone encounters a case where this assumption fails, please reopen this issue with details.

**Comment by inexorabletash** [comment]
Cool! Thanks for the quick response.

That said... A2D doesn't intentionally modify COUT; it just watches $C000/$C010 directly. However, the 80col firmware is enabled for the loading screens, and left enabled while A2D is running, and the 80col firmware points the COUT vector to C3Out. It looks like your heuristic sends $7F when the 80col firmware is active, e.g.:

Boot to BASIC
10 GET A$ : ?ASC(A$)
RUN
Pressing backspace yields 8
PR#3
RUN
Pressing backspace yields 127
